name: Trigger auto deployment for container-app-q2xzflxlbcgae

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-q2xzflxlbcgae-AutoDeployTrigger-d442bb88-fd93-4b50-bba8-c29342db4492.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryq2xzflxlbcgae.azurecr.io
          username: ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryq2xzflxlbcgae.azurecr.io/container-app-q2xzflxlbcgae:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-q2xzflxlbcgae -g swacosmostemplatea573b28a --server containerregistryq2xzflxlbcgae.azurecr.io --username  ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPQ2XZFLXLBCGAE_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-q2xzflxlbcgae -g swacosmostemplatea573b28a --image containerregistryq2xzflxlbcgae.azurecr.io/container-app-q2xzflxlbcgae:${{ github.sha }}
