name: Trigger auto deployment for container-app-5sdha73blwd5m

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-5sdha73blwd5m-AutoDeployTrigger-1aec4132-ec91-44db-8611-11af24af4466.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry5sdha73blwd5m.azurecr.io
          username: ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry5sdha73blwd5m.azurecr.io/container-app-5sdha73blwd5m:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-5sdha73blwd5m -g swacosmostemplatea5739c09 --server containerregistry5sdha73blwd5m.azurecr.io --username  ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP5SDHA73BLWD5M_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-5sdha73blwd5m -g swacosmostemplatea5739c09 --image containerregistry5sdha73blwd5m.azurecr.io/container-app-5sdha73blwd5m:${{ github.sha }}
