name: Trigger auto deployment for container-app-scvdd5oi5254a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-scvdd5oi5254a-AutoDeployTrigger-7f3ad1e9-880c-4c99-be98-47759320b05e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryscvdd5oi5254a.azurecr.io
          username: ${{ secrets.CONTAINERAPPSCVDD5OI5254A_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPSCVDD5OI5254A_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryscvdd5oi5254a.azurecr.io/container-app-scvdd5oi5254a:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSCVDD5OI5254A_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSCVDD5OI5254A_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSCVDD5OI5254A_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-scvdd5oi5254a -g swacosmostemplatea573b4b9 --server containerregistryscvdd5oi5254a.azurecr.io --username  ${{ secrets.CONTAINERAPPSCVDD5OI5254A_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPSCVDD5OI5254A_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-scvdd5oi5254a -g swacosmostemplatea573b4b9 --image containerregistryscvdd5oi5254a.azurecr.io/container-app-scvdd5oi5254a:${{ github.sha }}
